//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingVaccineService
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaccineUsage
    {
        public int id { get; set; }
        public string vaccine_code { get; set; }
        public string resident_nik { get; set; }
        public Nullable<System.DateTime> used_at { get; set; }
    }
}
