//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingVaccineClient.GovermentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GovermentService.IGovermentService")]
    public interface IGovermentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGovermentService/validate", ReplyAction="http://tempuri.org/IGovermentService/validateResponse")]
        bool validate(string NIK);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGovermentService/validate", ReplyAction="http://tempuri.org/IGovermentService/validateResponse")]
        System.Threading.Tasks.Task<bool> validateAsync(string NIK);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGovermentServiceChannel : TrackingVaccineClient.GovermentService.IGovermentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GovermentServiceClient : System.ServiceModel.ClientBase<TrackingVaccineClient.GovermentService.IGovermentService>, TrackingVaccineClient.GovermentService.IGovermentService {
        
        public GovermentServiceClient() {
        }
        
        public GovermentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GovermentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GovermentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GovermentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool validate(string NIK) {
            return base.Channel.validate(NIK);
        }
        
        public System.Threading.Tasks.Task<bool> validateAsync(string NIK) {
            return base.Channel.validateAsync(NIK);
        }
    }
}
